logsBucket: "gs://craffy-build-logs"

options:
  machineType: E2_HIGHCPU_8 # 8 vCPU
  logging: GCS_ONLY

timeout: "600s" # 10 minutes

steps:
  - name: "asia-east1-docker.pkg.dev/$PROJECT_ID/public/japanese-notes-parser:1.0.3"
    id: Run parser
    args:
      - create
      - -f
      - spoken_languages/japanese/vocabulary.md
      - -d
      - /workspace/japanese_vocab.db
      - --overwrite

  - name: "gcr.io/cloud-builders/gsutil"
    id: Upload db
    waitFor: [Run parser]
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        gsutil cp /workspace/japanese_vocab.db gs://alexhokl_public/japanese_vocab.db
